server:
  port: 9002
spring:
  application:
    name: AUTH-SERVICE
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    url: jdbc:mysql://localhost:3306/e_commerce?useSSL=false
    username : root
    password : root
  jpa:
    properties:
      hibernate :
        dialect : org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate :
      ddl-auto : update 
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
